### ISSUE TITLE
Release Build Fails with Error

### ISSUE THREAD

**Issue by DavinderJolly** [DavinderJolly/RustSnake#4]
# Release Build Fails to run due to Font file not being there

thread 'main' panicked at src\game.rs:31:88:
called `Result::unwrap()` on an `Err` value: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Steps to replicate:**
1. clone and cd into repo
2. run `cargo build --release`
3. cd into target/release and run the execuable

**Comment by BluePhoenix01** [comment]
I would like to fix this!
